### ISSUE TITLE
Respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by KCaverly** [KCaverly/peaches#6]
Inherit peaches path from xdg config.

**Comment by HacDan** [comment]
Are you just looking to change it to respect the `XDG_CONFIG_HOME` env variable?

**Comment by KCaverly** [comment]
I have one option now to read PEACHES_PATH if provided which provides custom paths. 

Maybe - if peaches path first, if xdg config second then default to home directory if neither are set?
